name: Build and Deploy

on:
  push:
    branches:
      - "develop"
    tags:
      - "force-cicd-*"
      - "test-*"
      - "release-*"

env:
  PROJECT_NAME: bitsmiley
  REPO_NAME: ${{ github.event.repository.name }}
  S3_BUCKET: 439863938209-static-websites
  DEPLOY_DEVELOP: develop
  DEPLOY_TEST: ^test-.*$
  DEPLOY_MAIN: ^release-.*$

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-20.04

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::439863938209:role/github-actions-cicd
          aws-region: ap-southeast-1

      - name: Initialize environment variables
        run: |
          S3_SUBPATH=$PROJECT_NAME/$(echo $REPO_NAME | tr "[:upper:]" "[:lower:]" | tr "_" "-" | tr "/" "-" | tr "." "-")

          # Determine if we are in the deploy branch
          CURRENT_ENV=${{ github.ref_name }}
          REF_TYPE=${{ github.ref_type }}
          if [[ $REF_TYPE == "branch" && $CURRENT_ENV == $DEPLOY_DEVELOP ]]; then
              echo "IS_DEPLOY=true" >> "$GITHUB_ENV"
              echo "IS_DEPLOY_DEVELOP=true" >> "$GITHUB_ENV"
              S3_SUBPATH=$S3_SUBPATH/develop
          elif [[ $REF_TYPE == "tag" && $CURRENT_ENV =~ $DEPLOY_TEST ]]; then
              echo "IS_DEPLOY=true" >> "$GITHUB_ENV"
              S3_SUBPATH=$S3_SUBPATH/test
          elif [[ $REF_TYPE == "tag" && $CURRENT_ENV =~ $DEPLOY_MAIN ]]; then
              echo "IS_DEPLOY_MAIN=true" >> "$GITHUB_ENV"
              S3_SUBPATH=$S3_SUBPATH/main
          fi

          echo "S3_SUBPATH=$S3_SUBPATH" >> $GITHUB_ENV

      - name: Run the build process
        if: env.IS_DEPLOY == 'true'
        run: |
          npm ci

          npm run build

      - name: Deploy to S3 dev
        if: env.IS_DEPLOY_DEVELOP == 'true'
        run: |
          aws s3 sync ./dist s3://$S3_BUCKET/$S3_SUBPATH/ --delete

          aws cloudfront create-invalidation --distribution-id EA1V5QWQJDZTR --paths "/*"
